### ISSUE TITLE
FEAT: Add responsiveness

### ISSUE THREAD

**Issue by thigazzz** [thigazzz/personal-portfolio#1]
## Description

Currently, the website is not responsive, which can frustrate the experience of users on different devices and screens. I will implement responsiveness so this doesn't happen

## Goals
- Make the project layout adaptable to different screen sizes
- Ensure page elements scale appropriately on mobile and tablet devices.

## Tasks
1.Update stylesheets (CSS) to include media rules that respond to different screen sizes.
2.Conduct testing on multiple devices to ensure changes are effective.

(first issue. i learning how to do this)

**Comment by thigazzz** [comment]
- [x] changing the layout to make the website fit on other devices
- [x] change dimension of elements

**Comment by thigazzz** [comment]
Complete addition of responsiveness. Testing on different device sizes. No elements breaking

**Comment by thigazzz** [comment]
## Description
The images are not at the appropriate resolution for different types of screens. This causes difficulty for the user to understand what is in the image, in addition to making the website look ugly. See:
![image](https://github.com/thigazzz/personal-portfolio/assets/86504455/827bcf36-06bf-4d9e-aa16-88e89a0a6bc0)

## Goals
- [ ] Make images following the growth of the projects displayed on the website (automation is better way)
- [ ] Adapt these images to different types of screens
